version: '3'

services:
  zlib:
    image: millelibri

    build:
      context: .
      dockerfile: ./Dockerfile

    restart: always

    ports:
      - "7070:7070"

    volumes:
      - ./index:/index